#cloud-config
version: 1
early-commands:
  - sudo systemctl stop ssh # during install only

locale: en_CH.UTF-8
keyboard:
  layout: ch
  variant: fr

storage:
  config:
    # Disk configuration
    - id: disk0
      name: disk0
      type: disk
      ptable: gpt
      preserve: true
      grub_device: false
      match:
        ssd: true    

    # ESP partition (EFI)
    - id: esp
      type: partition
      device: disk0
      size: 1G
      flag: boot
      number: 1
      wipe: superblock
      grub_device: true

    - id: esp-format
      type: format
      fstype: fat32
      volume: esp

    # Boot partition
    - id: boot
      type: partition
      device: disk0
      size: 2G
      number: 2

    - id: boot-format
      type: format
      fstype: ext4
      volume: boot

    # Root partition for LVM
    - id: root
      type: partition
      device: disk0
      size: 80G
      wipe: superblock
      number: 3

    # LVM Volume Group
    - id: vgroot
      type: lvm_volgroup
      name: vgroot
      devices: [root]

    # LVM Logical Volume
    - id: lvroot
      type: lvm_partition
      name: lvroot
      volgroup: vgroot
      wipe: superblock
      size: 20G

    # LUKS encryption
    - id: luroot
      type: dm_crypt
      dm_name: luroot
      volume: lvroot
      key: temporarypassword

    # Format LUKS volume
    - id: luroot-format
      type: format
      fstype: ext4
      volume: luroot

    # BTRFS partition
    - id: btrfs_part
      type: partition
      device: disk0
      size: -1
      number: 4

    # Format BTRFS partition
    - id: btrfs_format
      type: format
      fstype: btrfs
      volume: btrfs_part
      options: -f

    # Create BTRFS subvolumes
    - id: btrfs_root
      type: btrfs
      volume: btrfs_format
      path: /
      subvolumes:
        - path: home
          mountpoint: /home
        - path: snapshots
          mountpoint: /.snapshots
        - path: var
          mountpoint: /var
        - path: data
          mountpoint: /data

    # Mount points
    - id: luroot-mount
      type: mount
      device: luroot-format
      path: /

    - id: boot-mount
      type: mount
      device: boot-format
      path: /boot

    - id: esp-mount
      type: mount
      device: esp-format
      path: /boot/efi

    - id: home-mount
      type: mount
      device: btrfs_format
      path: /home
      options: subvol=home

    - id: snapshots-mount
      type: mount
      device: btrfs_format
      path: /.snapshots
      options: subvol=snapshots

    - id: var-mount
      type: mount
      device: btrfs_format
      path: /var
      options: subvol=var

    - id: data-mount
      type: mount
      device: btrfs_format
      path: /data
      options: subvol=data

identity:
  hostname: ubuntu
  username: ubuntu
  password: "$6$examplehash$Ga.TdB4XHHv.SqWWzXoAp8Rd0zRqHwwgDx0ZJpkhJgRdwq/IQR7xHb.lEG9UGQPzw8THqTL/kFHGJj5YEGr0e1" # Change this!

ssh:
  install-server: true
  allow-pw: true

packages:
  - btrfs-progs
  - cryptsetup
  - lvm2

user-data:
  disable_root: true
  timezone: Europe/Zurich
  locale: en_CH.UTF-8
  locale_configfile:
    path: /etc/default/locale
    content: |
      LANG=en_CH.UTF-8
      LC_TIME=fr_CH.UTF-8
      LC_MONETARY=fr_CH.UTF-8
      LC_PAPER=fr_CH.UTF-8
      LC_MEASUREMENT=fr_CH.UTF-8 